export const supportedLanguages = ['th', 'en', 'ja', 'ko', 'zh'] as const;
export type Language = (typeof supportedLanguages)[number];
type MessageKey = string;

const messages: Record<Language, Record<MessageKey, string>> = {
  th: { waiting:'กำลังรอวิดีโอ',ready:'พร้อม sync',syncing:'กำลัง sync เสียง',youtubeLink:'YouTube link',addTrack:'เพิ่มแทร็ก',youtubeOnly:'รองรับ youtube.com และ youtu.be เท่านั้น',playAll:'เล่นทั้งหมด',pauseAll:'หยุดชั่วคราว',masterPlayhead:'MASTER PLAYHEAD',fixDrift:'แก้ drift ตอนนี้',empty:'วาง YouTube link เพื่อเพิ่มแทร็กแรก',master:'MASTER',offset:'OFFSET',volume:'VOLUME',capture:'จับจุดนี้',invalidLink:'ใส่ YouTube link ที่ถูกต้อง',loading:'กำลังโหลด…',cannotLoad:'โหลดวิดีโอนี้ไม่ได้',waitForVideo:'รอให้วิดีโอโหลดครบก่อน',masterNoOffset:'Master ไม่ต้องตั้ง Offset',offsetCaptured:'จับ Offset แล้ว',error153:'ต้องเปิดผ่านเว็บไซต์หรือ localhost' },
  en: { waiting:'Waiting for video',ready:'Ready to sync',syncing:'Syncing audio',youtubeLink:'YouTube link',addTrack:'Add track',youtubeOnly:'youtube.com and youtu.be only',playAll:'Play all',pauseAll:'Pause all',masterPlayhead:'MASTER PLAYHEAD',fixDrift:'Fix drift now',empty:'Paste a YouTube link to add the first track',master:'MASTER',offset:'OFFSET',volume:'VOLUME',capture:'Capture here',invalidLink:'Enter a valid YouTube link',loading:'Loading…',cannotLoad:'This video cannot be loaded',waitForVideo:'Wait for all videos to load',masterNoOffset:'The Master needs no offset',offsetCaptured:'Offset captured',error153:'Open through a website or localhost' },
  ja: { waiting:'動画を待機中',ready:'同期の準備完了',syncing:'音声を同期中',youtubeLink:'YouTube リンク',addTrack:'トラックを追加',youtubeOnly:'youtube.com と youtu.be のみ対応',playAll:'すべて再生',pauseAll:'一時停止',masterPlayhead:'マスター再生位置',fixDrift:'ずれを修正',empty:'YouTube リンクを貼り付けて最初のトラックを追加',master:'マスター',offset:'オフセット',volume:'音量',capture:'この位置を取得',invalidLink:'有効な YouTube リンクを入力してください',loading:'読み込み中…',cannotLoad:'この動画を読み込めません',waitForVideo:'すべての動画が読み込まれるまで待ってください',masterNoOffset:'マスターにはオフセット不要です',offsetCaptured:'オフセットを取得しました',error153:'ウェブサイトまたは localhost から開いてください' },
  ko: { waiting:'동영상 대기 중',ready:'동기화 준비 완료',syncing:'오디오 동기화 중',youtubeLink:'YouTube 링크',addTrack:'트랙 추가',youtubeOnly:'youtube.com 및 youtu.be만 지원',playAll:'모두 재생',pauseAll:'일시 정지',masterPlayhead:'마스터 재생 위치',fixDrift:'드리프트 수정',empty:'YouTube 링크를 붙여 첫 트랙을 추가하세요',master:'마스터',offset:'오프셋',volume:'볼륨',capture:'이 지점 캡처',invalidLink:'올바른 YouTube 링크를 입력하세요',loading:'불러오는 중…',cannotLoad:'이 동영상을 불러올 수 없습니다',waitForVideo:'모든 동영상이 로드될 때까지 기다리세요',masterNoOffset:'마스터에는 오프셋이 필요 없습니다',offsetCaptured:'오프셋을 캡처했습니다',error153:'웹사이트 또는 localhost에서 여세요' },
  zh: { waiting:'正在等待视频',ready:'可以同步',syncing:'正在同步音频',youtubeLink:'YouTube 链接',addTrack:'添加轨道',youtubeOnly:'仅支持 youtube.com 和 youtu.be',playAll:'全部播放',pauseAll:'暂停',masterPlayhead:'主轨播放位置',fixDrift:'立即修正偏移',empty:'粘贴 YouTube 链接以添加第一个轨道',master:'主轨',offset:'偏移',volume:'音量',capture:'捕捉此位置',invalidLink:'请输入有效的 YouTube 链接',loading:'加载中…',cannotLoad:'无法加载此视频',waitForVideo:'请等待所有视频加载完成',masterNoOffset:'主轨无需设置偏移',offsetCaptured:'已捕捉偏移',error153:'请通过网站或 localhost 打开' },
};

let currentLanguage: Language = 'th';
const extras: Record<Language, Record<string, string>> = {
  th: { share:'สร้างลิงก์ Sync', copied:'คัดลอกลิงก์แล้ว', copyPrompt:'คัดลอกลิงก์นี้', footerTag:'หลายเวอร์ชัน · หนึ่งจังหวะ', footerHeading:'วิธีใช้', footerStep1:'วาง YouTube link ของแต่ละเวอร์ชันในช่องด้านบน', footerStep2:'เลือก Master แล้วเลื่อนแต่ละแทร็กไปยังคำร้องหรือ beat เดียวกัน ก่อนกด “จับจุดนี้”', footerStep3:'กดเล่นทั้งหมด แล้วปรับเสียงหรือ Offset เพิ่มได้ทุกเมื่อ', footerNote:'YouTube อาจให้กดปุ่มหนึ่งครั้งก่อนจึงจะเล่นพร้อมเสียงได้' },
  en: { share:'Share link', copied:'Link copied', copyPrompt:'Copy this link', footerTag:'Multiple versions, one moment.', footerHeading:'HOW TO USE', footerStep1:'Paste each YouTube link into the bar above.', footerStep2:'Pick a Master, then capture the same lyric or beat on every other track.', footerStep3:'Play all. Adjust volume or fine-tune Offset whenever needed.', footerNote:'YouTube may require one interaction before it can play with sound.' },
  ja: { share:'同期リンクを共有', copied:'リンクをコピーしました', copyPrompt:'このリンクをコピー', footerTag:'複数のバージョン、ひとつの瞬間。', footerHeading:'使い方', footerStep1:'上のバーに各 YouTube リンクを貼り付けます。', footerStep2:'マスターを選び、他のトラックを同じ歌詞またはビートに合わせて位置を取得します。', footerStep3:'すべて再生して、必要に応じて音量やオフセットを調整します。', footerNote:'音声付き再生には YouTube 上で一度操作が必要な場合があります。' },
  ko: { share:'동기화 링크 공유', copied:'링크를 복사했습니다', copyPrompt:'이 링크 복사', footerTag:'여러 버전, 하나의 순간.', footerHeading:'사용 방법', footerStep1:'위 입력창에 각 YouTube 링크를 붙여 넣으세요.', footerStep2:'마스터를 고르고 다른 트랙을 같은 가사나 비트에 맞춰 캡처하세요.', footerStep3:'모두 재생한 뒤 필요하면 볼륨이나 오프셋을 조절하세요.', footerNote:'소리와 함께 재생하려면 YouTube에서 한 번의 조작이 필요할 수 있습니다.' },
  zh: { share:'分享同步链接', copied:'链接已复制', copyPrompt:'复制此链接', footerTag:'多个版本，同一时刻。', footerHeading:'使用方法', footerStep1:'将每个 YouTube 链接粘贴到上方输入框。', footerStep2:'选择主轨，然后在其他轨道捕捉相同歌词或节拍的位置。', footerStep3:'全部播放，并随时调节音量或微调偏移。', footerNote:'YouTube 可能需要一次操作后才能播放声音。' },
};
export function setLanguage(language: Language) { currentLanguage = language; document.documentElement.lang = language === 'zh' ? 'zh-CN' : language; localStorage.setItem('syncsound-language', language); }
export function getLanguage(): Language { return currentLanguage; }
export function t(key: MessageKey): string { return messages[currentLanguage][key] ?? extras[currentLanguage][key] ?? key; }
export function translatePage() { document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((node) => { const key = node.dataset.i18n as MessageKey; node.textContent = t(key); }); }
export function preferredLanguage(): Language { const saved = localStorage.getItem('syncsound-language'); if (supportedLanguages.includes(saved as Language)) return saved as Language; const browser = navigator.language.toLowerCase(); if (browser.startsWith('ja')) return 'ja'; if (browser.startsWith('ko')) return 'ko'; if (browser.startsWith('zh')) return 'zh'; if (browser.startsWith('th')) return 'th'; return 'en'; }
