import './style.css';
import { getLanguage, preferredLanguage, setLanguage, supportedLanguages, t, translatePage, type Language } from './i18n';

type Player = { getCurrentTime(): number; playVideo(): void; pauseVideo(): void; seekTo(seconds: number, allowSeekAhead: boolean): void; setPlaybackRate(rate: number): void; setVolume(volume: number): void; destroy(): void; getVideoData(): { title?: string } };
type Track = { id: string; videoId: string; card: HTMLElement; player: Player | null; ready: boolean; offset: number; volume: number };
type SavedTrack = { id: string; o?: number; v?: number; m?: boolean };
declare global { interface Window { onYouTubeIframeAPIReady?: () => void; YT?: { Player: new (id: string, options: unknown) => Player } } }

const tracks: Track[] = []; let masterId: string | null = null; let apiReady = false; let timer: number | undefined;
const $ = <T extends HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
function makeId() { return globalThis.crypto?.randomUUID?.() ?? `video-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`; }

function setStatus(message: string, state = '') { const node = $('#syncState'); node.className = `sync-state ${state}`; node.querySelector('span')!.textContent = message; }
function getMaster() { return tracks.find((track) => track.id === masterId) ?? tracks[0]; }
function clock(seconds: number) { if (!Number.isFinite(seconds)) return '00:00.000'; const m = Math.floor(seconds / 60); const s = Math.floor(seconds % 60); const ms = Math.floor((seconds % 1) * 1000); return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`; }
function setOffset(track: Track, value: number) { track.offset = Math.round(value * 1000) / 1000; track.card.querySelector<HTMLInputElement>('.offset')!.value = String(track.offset); }
function enableControls() { ['playAll','pauseAll','syncNow','shareLink'].forEach((id) => { $<HTMLButtonElement>(`#${id}`).disabled = !tracks.length; }); }
function videoIdFrom(value: string) { try { const url = new URL(value.trim()); if (url.hostname === 'youtu.be') return url.pathname.split('/')[1]; if (url.hostname.endsWith('youtube.com')) return url.searchParams.get('v') ?? url.pathname.split('/').filter(Boolean).pop(); } catch { /* input validation handles this */ } return null; }
function emptyState() { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.id = 'emptyState'; empty.innerHTML = `<span>＋</span><p>${t('empty')}</p>`; return empty; }
function updateTrackText() { tracks.forEach((track) => { track.card.querySelector('[data-key="master"]')!.textContent = t('master'); track.card.querySelector('[data-key="offset"]')!.textContent = t('offset'); track.card.querySelector('[data-key="volume"]')!.textContent = t('volume'); track.card.querySelector('[data-key="capture"]')!.textContent = t('capture'); }); }

function addTrack(videoId: string, saved?: SavedTrack) {
  const card = document.createElement('article'); card.className = 'track'; const id = makeId();
  const offset = Number.isFinite(saved?.o) ? saved!.o! : 0; const volume = Math.min(100, Math.max(0, Number.isFinite(saved?.v) ? saved!.v! : 100)); const isMaster = saved?.m || !masterId;
  card.innerHTML = `<div class="track-bar"><span class="track-index">TRACK ${String(tracks.length + 1).padStart(2,'0')}</span><label class="master-choice"><input type="radio" name="master" ${isMaster ? 'checked' : ''}><span data-key="master">${t('master')}</span></label><button class="remove-track" aria-label="Remove track">×</button></div><div class="player-wrap"><div class="player" id="${id}"></div></div><div class="track-footer"><div class="track-name">${t('loading')}</div><div class="controls"><div class="offset-group"><span class="control-label" data-key="offset">${t('offset')}</span><div class="offset-box"><input class="offset" type="number" value="${offset}" step="0.05"><small>s</small></div><div class="offset-tools"><button class="nudge" data-value="-0.05">−</button><button class="capture" data-key="capture">${t('capture')}</button><button class="nudge" data-value="0.05">+</button></div></div><label class="volume-group"><span class="control-label" data-key="volume">${t('volume')}</span><input class="volume-range" type="range" min="0" max="100" value="${volume}"><output class="volume-value">${volume}%</output></label><div class="drift"><span>DRIFT</span><output>—</output></div></div></div>`;
  const track: Track = { id, videoId, card, player: null, ready: false, offset, volume }; if (isMaster) masterId = id;
  card.querySelector<HTMLInputElement>('input[type=radio]')!.addEventListener('change', () => { masterId = id; setStatus(t('ready'), 'ready'); });
  card.querySelector<HTMLInputElement>('.offset')!.addEventListener('input', (event) => setOffset(track, Number((event.target as HTMLInputElement).value) || 0));
  card.querySelectorAll<HTMLButtonElement>('.nudge').forEach((button) => button.addEventListener('click', () => { setOffset(track, track.offset + Number(button.dataset.value)); synchronize(true); }));
  card.querySelector<HTMLButtonElement>('.capture')!.addEventListener('click', () => { const master = getMaster(); if (!master?.ready || !track.ready) return setStatus(t('waitForVideo'), 'warning'); if (master === track) return setStatus(t('masterNoOffset')); setOffset(track, track.player!.getCurrentTime() - master.player!.getCurrentTime()); setStatus(t('offsetCaptured'), 'ready'); });
  card.querySelector<HTMLInputElement>('.volume-range')!.addEventListener('input', (event) => { track.volume = Number((event.target as HTMLInputElement).value); card.querySelector('.volume-value')!.textContent = `${track.volume}%`; track.player?.setVolume(track.volume); });
  card.querySelector<HTMLButtonElement>('.remove-track')!.addEventListener('click', () => removeTrack(track));
  $('#desk').append(card); $('#emptyState')?.remove(); tracks.push(track); enableControls();
  const origin = /^https?:$/.test(window.location.protocol) ? window.location.origin : undefined;
  track.player = new window.YT!.Player(id, { videoId, playerVars: { playsinline: 1, rel: 0, ...(origin ? { origin } : {}) }, events: { onReady: (event: { target: Player }) => { track.ready = true; track.player = event.target; track.player.setVolume(track.volume); card.querySelector('.track-name')!.textContent = track.player.getVideoData().title ?? 'YouTube video'; setStatus(t('ready'), 'ready'); }, onError: (event: { data: number }) => { card.querySelector('.track-name')!.textContent = event.data === 153 ? t('error153') : t('cannotLoad'); setStatus(`YouTube error ${event.data}`, 'warning'); } } });
}
function removeTrack(track: Track) { const index = tracks.indexOf(track); if (index < 0) return; track.player?.destroy(); tracks.splice(index, 1); track.card.remove(); if (masterId === track.id) { masterId = tracks[0]?.id ?? null; const radio = tracks[0]?.card.querySelector<HTMLInputElement>('input[type=radio]'); if (radio) radio.checked = true; } tracks.forEach((item, i) => item.card.querySelector('.track-index')!.textContent = `TRACK ${String(i + 1).padStart(2,'0')}`); if (!tracks.length) { $('#desk').append(emptyState()); setStatus(t('waiting')); } enableControls(); }
function synchronize(hard = false) { const master = getMaster(); if (!master?.ready) return; const masterTime = master.player!.getCurrentTime(); ($<HTMLOutputElement>('#masterClock')).value = clock(masterTime); tracks.filter((track) => track !== master && track.ready).forEach((track) => { const desired = Math.max(0, masterTime + track.offset); const delta = desired - track.player!.getCurrentTime(); const display = track.card.querySelector<HTMLOutputElement>('.drift output')!; display.value = `${delta >= 0 ? '+' : ''}${delta.toFixed(3)}s`; if (hard || Math.abs(delta) > .35) { track.player!.setPlaybackRate(1); track.player!.seekTo(desired, true); } else if (Math.abs(delta) > .045) track.player!.setPlaybackRate(delta > 0 ? 1.08 : .92); else track.player!.setPlaybackRate(1); }); }
function playAll() { const master = getMaster(); if (!master?.ready) return setStatus(t('waitForVideo'), 'warning'); const current = master.player!.getCurrentTime(); tracks.filter((track) => track !== master && track.ready).forEach((track) => { track.player!.seekTo(Math.max(0, current + track.offset), true); track.player!.playVideo(); }); master.player!.playVideo(); window.clearInterval(timer); timer = window.setInterval(() => synchronize(), 150); setStatus(t('syncing'), 'ready'); }
function encodeSession() { const payload = JSON.stringify({ v: 1, t: tracks.map((track) => ({ id: track.videoId, o: track.offset, v: track.volume, m: track.id === masterId })) }); const bytes = new TextEncoder().encode(payload); return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''); }
function decodeSession(): SavedTrack[] | null { try { const value = new URLSearchParams(window.location.hash.slice(1)).get('s'); if (!value) return null; const base64 = value.replaceAll('-','+').replaceAll('_','/') + '==='.slice((value.length + 3) % 4); const data = JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(base64), (char) => char.charCodeAt(0)))); if (!Array.isArray(data?.t)) return null; return data.t.filter((track: unknown): track is SavedTrack => typeof (track as SavedTrack)?.id === 'string' && /^[A-Za-z0-9_-]{6,}$/.test((track as SavedTrack).id)).slice(0, 12); } catch { return null; } }
function restoreSession() { const savedTracks = decodeSession(); if (!savedTracks?.length) return; savedTracks.forEach((track) => addTrack(track.id, track)); const master = tracks.find((track, index) => savedTracks[index]?.m) ?? tracks[0]; masterId = master.id; tracks.forEach((track) => { track.card.querySelector<HTMLInputElement>('input[type=radio]')!.checked = track.id === masterId; }); setStatus(t('ready'), 'ready'); }
async function shareSession() { const url = new URL(window.location.href); url.hash = `s=${encodeSession()}`; history.replaceState(null, '', url); try { await navigator.clipboard.writeText(url.href); setStatus(t('copied'), 'ready'); } catch { window.prompt(t('copyPrompt'), url.href); } }
function loadYouTube() { const script = document.createElement('script'); script.src = 'https://www.youtube.com/iframe_api'; window.onYouTubeIframeAPIReady = () => { apiReady = true; restoreSession(); setStatus(tracks.length ? t('ready') : t('waiting'), tracks.length ? 'ready' : ''); }; document.head.append(script); }

setLanguage(preferredLanguage()); ($<HTMLSelectElement>('#language')).value = getLanguage(); translatePage(); $('#shareLabel').textContent = t('share');
$('#language').addEventListener('change', (event) => { setLanguage((event.target as HTMLSelectElement).value as Language); translatePage(); updateTrackText(); $('#shareLabel').textContent = t('share'); if (!tracks.length) $('#emptyState p')!.textContent = t('empty'); });
$('#addForm').addEventListener('submit', (event) => { event.preventDefault(); const input = $('#youtubeUrl') as HTMLInputElement; const videoId = videoIdFrom(input.value); if (!videoId) return setStatus(t('invalidLink'), 'warning'); if (!apiReady) return setStatus(t('waiting'), 'warning'); addTrack(videoId); input.value = ''; });
$('#playAll').addEventListener('click', playAll); $('#pauseAll').addEventListener('click', () => { tracks.forEach((track) => track.ready && track.player!.pauseVideo()); window.clearInterval(timer); setStatus(t('waiting')); }); $('#syncNow').addEventListener('click', () => synchronize(true));
$('#shareLink').addEventListener('click', shareSession);
loadYouTube();
